version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    hostname: elasticsearch
    privileged: true
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 9200:9200
    volumes:
      - ../../data/elasticsearch/usr/share/elasticsearch/data/:/usr/share/elasticsearch/data/
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    hostname: kibana
    environment:
      - 'elasticsearch.hosts=http://elasticsearch:9200'
      - 'elasticsearch.username=elastic'
      - 'elasticsearch.password=elastic'
      - 'i18n.locale=zh-CN'

    ports:
      - 5601:5601

networks:
  default:
    external: true
    name: local