version: "3"

services:
  neo4j:
    image: neo4j:4.3
    container_name: neo4j
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ../../data/neo4j/data:/data/

networks:
  default:
    external: true
    name: local
