services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.1
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr                internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr      internal://redpanda:9092,external://192.168.31.101:19092
      - --pandaproxy-addr           internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://192.168.31.101:18082
      - --schema-registry-addr      internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr                  redpanda:33145
      - --advertise-rpc-addr        redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 9644:9644
    volumes:
      - redpanda-data:/var/lib/redpanda/data

volumes:
  redpanda-data:

networks:
  default:
    name: compose
    external: true
