---
apiVersion: v1
kind: Service
metadata:
  namespace: redpanda
  name: redpanda-internal
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redpanda
  ports:
    - { "name": "kafka", "port": 9092 }
    - { "name": "http", "port": 8082 }
    - { "name": "schema-registry", "port": 8081 }
    - { "name": "admin", "port": 9644 }
    - { "name": "rpc", "port": 33145 }

---
apiVersion: v1
kind: Service
metadata:
  namespace: redpanda
  name: redpanda-external
  annotations:
    "metallb.universe.tf/allow-shared-ip": "192.168.31.130"
    "metallb.universe.tf/loadBalancerIPs": "192.168.31.130"
spec:
  type: LoadBalancer
  selector:
    app: redpanda
  ports:
    - { "name": "kafka", "port": 19092 }
    - { "name": "http", "port": 18082 }
    - { "name": "schema-registry", "port": 18081 }
    - { "name": "admin", "port": 9644 }
    - { "name": "rpc", "port": 33145 }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: redpanda
  name: redpanda
spec:
  selector:
    matchLabels:
      app: redpanda
  serviceName: redpanda-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      initContainers:
        - name: init
          image: 10.22.1.2:5000/docker.io/bitnami/os-shell:latest
          command: ["chmod", "-R", "777", "/var/lib/redpanda/data"]
          volumeMounts:
            - { "name": "data", "mountPath": "/var/lib/redpanda/data" }
          securityContext:
            runAsUser: 0
      containers:
        - name: redpanda
          image: 10.22.1.2:5000/docker.redpanda.com/redpandadata/redpanda:v24.3.1
          args:
            - redpanda
            - start
            - --kafka-addr                internal://0.0.0.0:9092,external://0.0.0.0:19092
            - --advertise-kafka-addr      internal://redpanda-0.redpanda-internal.redpanda.svc.cluster.local:9092,external://192.168.31.130:19092
            - --pandaproxy-addr           internal://0.0.0.0:8082,external://0.0.0.0:18082
            - --advertise-pandaproxy-addr internal://redpanda-internal.default.svc.cluster.local:8082,external://192.168.31.130:18082
            - --schema-registry-addr      internal://0.0.0.0:8081,external://0.0.0.0:18081
            - --rpc-addr                  redpanda-0.redpanda-internal.redpanda.svc.cluster.local:33145
            - --advertise-rpc-addr        redpanda-0.redpanda-internal.redpanda.svc.cluster.local:33145
            - --mode dev-container
            - --smp 1
            - --default-log-level=info
          ports:
            - { "containerPort": 9092 }
            - { "containerPort": 19092 }
            - { "containerPort": 8082 }
            - { "containerPort": 18082 }
            - { "containerPort": 8081 }
            - { "containerPort": 18081 }
            - { "containerPort": 9644 }
            - { "containerPort": 33145 }
          volumeMounts:
            - { "name": "data", "mountPath": "/var/lib/redpanda/data" }

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
