---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: redpanda
  name: redpanda-console
data:
  "config.yaml": |
    kafka:
      brokers:
        - redpanda-external.redpanda.svc.cluster.local:19092
      sasl:
        enabled: true
        username: admin
        password: admin
        mechanism: SCRAM-SHA-512
      # schemaRegistry:
      #   enabled: true
      #   urls:
      #     - http://redpanda-external.redpanda.svc.cluster.local:18081
      #   # username: admin
      #   # password: admin
    redpanda:
      adminApi:
        enabled: true
        urls:
          - http://redpanda-external.redpanda.svc.cluster.local:9644

---
apiVersion: v1
kind: Service
metadata:
  namespace: redpanda
  name: redpanda-console-external
  annotations:
    "metallb.universe.tf/allow-shared-ip": "192.168.31.130"
    "metallb.universe.tf/loadBalancerIPs": "192.168.31.130"
spec:
  type: LoadBalancer
  selector:
    app: redpanda-console
  ports:
    - { "port": 8080 }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: redpanda
  name: redpanda-console
spec:
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      volumes:
        - name: redpanda-console
          configMap:
            name: redpanda-console
      containers:
        - name: redpanda-console
          image: 10.22.1.2:5000/docker.redpanda.com/redpandadata/console:v2.8.1
          env:
            - { name: CONFIG_FILEPATH, value: "/config.yaml" }
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /config.yaml
              subPath: config.yaml
              name: redpanda-console
