spring:
  datasource:
    url: jdbc:mysql://192.192.192.101:3306/demo
    username: root
    password: root
  redis:
    host: 192.192.192.101
    port: 6379
    database: 0
    username: default
    password: 1234
logging:
  level:
    xyz.icefery.demo.dao: debug
