version: '3'

services:
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    ports:
      - 6379:6379
    volumes:
      - ./redis/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    # restart: always
    ports:
      - 8001:8001

networks:
  default:
    external:
      name: local-net
