services:
  postgresql:
    image: docker.io/bitnami/postgresql:16.4.0
    container_name: postgresql
    user: root
    environment:
      TZ: Asia/Shanghai
      POSTGRESQL_POSTGRES_PASSWORD: postgres
      POSTGRESQL_DATABASE: demo
      POSTGRESQL_USERNAME: demo
      POSTGRESQL_PASSWORD: demo
      POSTGRESQL_TIMEZONE: Asia/Shanghai
      POSTGRESQL_LOG_TIMEZONE: Asia/Shanghai
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/bitnami/postgresql/data

networks:
  default:
    name: compose
    external: true

volumes:
  postgresql-data:
