apiVersion: v1
kind: ConfigMap
metadata:
  name: zeppelin
  namespace: dev
data:
  "zeppelin-env.sh": |
    export ZEPPELIN_ADDR="0.0.0.0"
    export ZEPPELIN_PORT="8080"
    export ZEPPELIN_RUN_MODE="local"

---
apiVersion: v1
kind: Service
metadata:
  name: zeppelin
  namespace: dev
  annotations:
    metallb.universe.tf/allow-shared-ip: 10.22.1.246
    metallb.universe.tf/loadBalancerIPs: 10.22.1.246
spec:
  selector:
    app: zeppelin
  type: LoadBalancer
  ports:
    - { name: "http", port: 8080, targetPort: 8080 }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeppelin
  namespace: dev
spec:
  selector:
    matchLabels:
      app: zeppelin
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      volumes:
        - name: config
          configMap:
            name: zeppelin
      containers:
        - name: zeppelin
          image: docker.io/apache/zeppelin:0.12.0
          ports:
            - { name: "http", containerPort: 8080 }
          volumeMounts:
            - { name: "config", mountPath: "/opt/zeppelin/conf/zeppelin-env.sh", subPath: "zeppelin-env.sh" }
