version: '3'

services:
  elasticsearch:
    image: elasticsearch
    # restart: always
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/plugins/:/usr/share/elasticsearch/plugins/
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    kibana:
      image: kibana
      # restart: always
      ports:
        - 5601:5601
      volumes:
        - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  default:
    external:
      name: local-net
