version: '3'

services:
  kibana:
    image: kibana:7.14.0
    container_name: kibana
    hostname: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
      - 'ELASTICSEARCH_USERNAME=elastic'
      - 'ELASTICSEARCH_PASSWORD=elastic'
      - 'I18N_LOCALE=zh-CN'
    ports:
      - 5601:5601
    volumes:
      - /d/share/:/d/share/

networks:
  default:
    external: true
    name: local
