version: '3.8'

services:
  tomcat_8080:
    image: tomcat
    # restart: always
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - ./tomcat0/data/:/usr/local/tomcat/webapps/

networks:
  default:
    external:
      name: local-net
