persistence:
  defaultClassReplicaCount: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

defaultSettings:
  defaultDataPath: /data/longhorn
  defaultReplicaCount: 1
  deletingConfirmationFlag: true

longhornUI:
  replicas: 1

ingress:
  enabled: true
  host: longhorn.example.org
