---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

### prometheus
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: prometheus
  targetNamespace: monitoring
  valuesContent: |-
    alertmanager:
      enabled: false
    server:
      extraScrapeConfigs:
        - job_name: 'node-exporter'
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: replace
              source_labels: [ __address__ ]
              regex: '(.*):10250'
              replacement: '${1}:9100'
              target_label: __address__
      ingress:
        enabled: true
        hostname: prometheus.example.org
      service:
        type: LoadBalancer


### node-exporter
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: node-exporter
  targetNamespace: monitoring

### grafana
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: grafana
  targetNamespace: monitoring
  valuesContent: |-
    admin:
      user: admin
      password: admin
    datasources:
      secretDefinition:
        datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            orgId: 1
            url: http://prometheus-server.monitoring.svc.cluster.local
            version: 1
            editable: true
            isDefault: true
    persistence:
      enabled: true
      size: 8Gi
    service:
      type: LoadBalancer
    ingress:
      enabled: true
      hostname: grafana.example.org
    metrics:
      enabled: true
