---
apiVersion: v1
kind: Service
metadata:
  namespace: local
  name: clash
spec:
  selector:
    app: clash
  type: NodePort
  ports:
    - port: 7890
      targetPort: 7890
      nodePort: 7890
    - port: 7891
      targetPort: 7891
      nodePort: 7891

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: local
  name: clash
spec:
  selector:
    matchLabels:
      app: clash
  template:
    metadata:
      labels:
        app: clash
    spec:
      containers:
        - name: clash
          image: dreamacro/clash:v1.10.6
          args:
            - -f /config.yml
          ports:
            - containerPort: 7890
            - containerPort: 7891
          volumeMounts:
            - mountPath: /config.yml
              name: config
      volumes:
        - name: config
          hostPath:
            path: /d/mount/clash/config.yml
            type: File
