apiVersion: v1
kind: Service
metadata:
  namespace: local
  name: clash
  labels:
    app: clash
spec:
  selector:
    app: clash
  type: NodePort
  ports:
    - port: 7890
      targetPort: 7890
      nodePort: 7890
    - port: 7891
      targetPort: 7891
      nodePort: 7891