version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    privileged: true
    # restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/var/lib/rabbitmq/mnesia/:/var/lib/rabbitmq/mnesia/

networks:
  default:
    external:
      name: local-net
