---
kind: Service
metadata:
  name: db2
spec:
  selector:
    app.kubernetes.io/name: db2
    app.kubernetes.io/component: database
  ports:
    - port: 50000
      targetPort: db2
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: db2-headless
spec:
  clusterIP: None
  ports:
    - port: 50000
      targetPort: db2
  selector:
    app.kubernetes.io/name: db2
    app.kubernetes.io/component: database
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: db2
      app.kubernetes.io/component: database
  serviceName: db2-headless
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db2
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: db2
          image: ibmcom/db2:11.5.5.0
          imagePullPolicy: IfNotPresent
          env:
            - name: LICENSE
              value: accept
            - name: DB2INST1_PASSWORD
              value: db2inst1
            - name: DBNAME
              value: demo
          ports:
            - containerPort: 50000
              name: db2
          volumeMounts:
            - name: db2
              mountPath: /database
  volumeClaimTemplates:
    - metadata:
        name: db2
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
