---
apiVersion: v1
kind: Service
metadata:
  name: clash
spec:
  selector:
    app: clash
  ports:
    - { name: clash, port: 7890 }
    - { name: yacd, port: 80 }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: clash
  labels:
    app: clash
spec:
  selector:
    matchLabels:
      app: clash
  template:
    metadata:
      labels:
        app: clash
    spec:
      containers:
        - name: clash
          image: ghcr.io/dreamacro/clash-premium:2023.08.17
          ports:
            - { name: clash, containerPort: 7890 }
          volumeMounts:
            - { name: config, mountPath: /root/.config/clash/config.yaml, subPath: config.yaml }
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
        - name: yacd
          image: ghcr.io/haishanh/yacd:v0.3.8
          ports:
            - { name: yacd, containerPort: 80 }
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: clash
