services:
  clash:
    image: dreamacro/clash:v1.11.0
    container_name: clash
    command: ['-f', '/config.yaml']
    ports:
      - 7890:7890
      - 7891:7891
    volumes:
      - /d/mount/clash/config.yaml:/config.yaml

networks:
  default:
    external: true
    name: compose
