version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - /d/share/:/d/share/

networks:
  default:
    external: true
    name: local
