mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url:
    username:
    password:
