global:
  scrape_timeout: 10s
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.8.101:9090"]
  - job_name: "pushgateway"
    static_configs:
      - targets: ["192.168.8.101:9091"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.8.101:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.8.101:8080"]
  - job_name: "starrocks"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["192.168.8.101:8030"]
        labels:
          group: fe
      - targets: ["192.168.8.101:8040", "192.168.8.102:8040", "192.168.8.103:8040"]
        labels:
          group: be
