version: '3'

services:
  postgresql:
    image: postgres:13.2
    container_name: postgresql
    # restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=root

networks:
  default:
    external:
      name: standalone-net
