version: '3.8'

services:
  redis0:
    image: redis
    # restart: always
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis0/conf/redis.conf:/usr/local/etc/redis/redis.conf

networks:
  default:
    external:
      name: local-net
