### harbor
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harbor
  namespace: default
  labels:
    app: harbor
spec:
  repo: https://coredns.github.io/helm
  chart: coredns
  targetNamespace: default
  bootstrap: true
  valuesContent: |-
    adminPassword: admin
    externalURL: http://192.168.8.101:30080
    ipFamily:
      ipv6:
        enabled: false
      ipv4:
        enabled: true
    exposureType: proxy
    service:
      type: LoadBalancer
    nginx:
      tls:
        enabled: false
    metrics:
      enabled: true
