version: "3"

services:
  oracle: 
    image: oracle/database:18.4.0-xe
    container_name: oracle
    hostname: oracle
    environment: 
      - ORACLE_PWD=0000
    ports: 
      - 1521:1521
    volumes: 
      - ./oracle/opt/oracle/oradata/:/opt/oracle/oradata/
      
networks:
  default:
    external: true
    name: local