deployment:
  kind: DaemonSet

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true

  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowEmptyServices: true
    publishedService:
      enabled: true

ports:
  traefik:
    port: 9000
    hostPort: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP
  web:
    port: 80
    hostPort: 80
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    hostPort: 443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true

service:
  type: ClusterIP
  externalIPs:
    - 192.192.192.6

hostNetwork: true

nodeSelector:
  kubernetes.io/hostname: dev

ecurityContext:
  capabilities:
    drop: []
    add:
      - ALL
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

podSecurityContext:
  fsGroup: 0
