ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    nodePort: 9000
    protocol: TCP
  web:
    port: 80
    expose: true
    exposedPort: 80
    nodePort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: true
    exposedPort: 443
    nodePort: 443
    protocol: TCP
    tls:
      enabled: true

service:
  type: NodePort

securityContext:
  capabilities:
    drop: []
    add:
      - ALL
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

podSecurityContext:
  fsGroup: 0
