deployment:
  kind: Deployment

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowEmptyServices: true
    publishedService:
      enabled: true

logs:
  general:
    level: INFO

ports:
  traefik:
    port: 9000
    protocol: TCP
    expose: true
    exposedPort: 9000
    # hostPort: 9000
    nodePort: 9000
  web:
    port: 80
    protocol: TCP
    expose: true
    exposedPort: 80
    # hostPort: 80
    nodePort: 80
  websecure:
    port: 443
    protocol: TCP
    expose: true
    exposedPort: 443
    # hostPort: 443
    nodePort: 443
    tls:
      enabled: true

service:
  type: NodePort
  externalIPs:
    - 192.192.192.6

hostNetwork: false

# nodeSelector:
#   kubernetes.io/hostname: dev

securityContext:
  capabilities:
    drop: []
    add:
      - ALL
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

podSecurityContext:
  fsGroup: 0
