apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  annotations:
    selectdb/doriscluster: doris
  labels:
    "app.kubernetes.io/instance": doris
    "app.kubernetes.io/name": doriscluster
    "app.kubernetes.io/part-of": doris-operator
  name: doris
  namespace: doris
spec:
  adminUser:
    name: root
    password: root
  beSpec:
    envVars:
      - name: TZ
        value: Asia/Shanghai
    image: selectdb/doris.be-ubuntu:2.1.7
    persistentVolumes:
      - mountPath: /opt/apache-doris/be/storage
        name: be-storage
        persistentVolumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
      - mountPath: /opt/apache-doris/be/log
        name: be-log
        persistentVolumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    replicas: 1
    requests:
      cpu: 2
      memory: 4Gi
    service:
      annotations:
        "metallb.universe.tf/allow-shared-ip": 192.168.1.133
        "metallb.universe.tf/loadBalancerIPs": 192.168.1.133
      type: LoadBalancer
    systemInitialization:
      command:
        - /sbin/sysctl
        - -w
        - vm.max_map_count=2000000
      initImage: selectdb/alpine:latest
  feSpec:
    electionNumber: 1
    envVars:
      - name: TZ
        value: Asia/Shanghai
    image: selectdb/doris.fe-ubuntu:2.1.7
    persistentVolumes:
      - mountPath: /opt/apache-doris/fe/doris-meta
        name: fe-meta
        persistentVolumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
      - mountPath: /opt/apache-doris/fe/log
        name: fe-log
        persistentVolumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    replicas: 1
    requests:
      cpu: 4
      memory: 8Gi
    service:
      annotations:
        "metallb.universe.tf/allow-shared-ip": 192.168.1.133
        "metallb.universe.tf/loadBalancerIPs": 192.168.1.133
      type: LoadBalancer
    systemInitialization:
      command:
        - /sbin/sysctl
        - -w
        - vm.max_map_count=2000000
      initImage: selectdb/alpine:latest
