apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  annotations:
    selectdb/doriscluster: doris
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
  name: doris
  namespace: doris
spec:
  feSpec:
    replicas: 3
    image: selectdb/doris.fe-ubuntu:2.0.2
    service:
      type: LoadBalancer
    envVars:
      - name: TZ
        value: Asia/Shanghai
    systemInitialization:
      command: ['/sbin/sysctl', '-w', 'vm.max_map_count=2000000']
  beSpec:
    replicas: 3
    image: selectdb/doris.be-ubuntu:2.0.2
    service:
      type: ClusterIP
    envVars:
      - name: TZ
        value: Asia/Shanghai
    systemInitialization:
      command: ['/sbin/sysctl', '-w', 'vm.max_map_count=2000000']
