apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  annotations:
    selectdb/doriscluster: doris
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
  name: doris
  namespace: doris
spec:
  feSpec:
    replicas: 1
    image: selectdb/doris.fe-ubuntu:3.0.2
    service:
      type: LoadBalancer
      servicePorts:
        - { targetPort: 8030, nodePort: 8030 }
        - { targetPort: 9010, nodePort: 9010 }
        - { targetPort: 9020, nodePort: 9020 }
        - { targetPort: 9030, nodePort: 9030 }
    envVars:
      - { name: TZ, value: Asia/Shanghai }
    systemInitialization:
      command: ["/sbin/sysctl", "-w", "vm.max_map_count=2000000"]
  beSpec:
    replicas: 1
    image: selectdb/doris.be-ubuntu:3.0.2
    service:
      type: LoadBalancer
      servicePorts:
        - { targetPort: 8040, nodePort: 8040 }
        - { targetPort: 9050, nodePort: 9050 }
        - { targetPort: 8060, nodePort: 8060 }
        - { targetPort: 9060, nodePort: 9060 }
    envVars:
      - { name: TZ, value: Asia/Shanghai }
    systemInitialization:
      command: ["/sbin/sysctl", "-w", "vm.max_map_count=2000000"]
