services:
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/bitnami/elasticsearch

networks:
  default:
    external: true
    name: compose

volumes:
  elasticsearch:
