services:
  kibana:
    image: docker.io/bitnami/kibana:8
    container_name: kibana
    environment:
      KIBANA_ELASTICSEARCH_URL: elasticsearch
      I18N_LOCALE: zh-CN
    ports:
      - 5601:5601
    volumes:
      - kibana:/bitnami/kibana

networks:
  default:
    external: true
    name: compose

volumes:
  kibana:
