services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=root:0000
    ports:
      - 1433:1433
    volumes:
      - /d/share/:/d/share/
      - /d/mount/sqlserver/var/opt/mssql/data/:/var/opt/mssql/data/

networks:
  default:
    external: true
    name: local
