services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=root:0000
    ports:
      - 1433:1433
    volumes:
      - sqlserver-data:/var/opt/mssql/

networks:
  default:
    external: true
    name: compose

volumes:
  sqlserver-data:
