version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --lower_case_table_names=1
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-time-zone=+8:00
