services:
  mysql:
    image: bitnami/mysql:8.0.32
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_EXTRA_FLAGS: '--lower-case-table-names=1'
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/bitnami/mysql/data

networks:
  default:
    external: true
    name: compose

volumes:
  mysql-data:
