version: "3"

services:
  rancher:
    image: rancher/rancher
    container_name: rancher
    hostname: rancher
    ports:
      - 1080:80
    volumes:
      - /d/share/:/d/share/

networks:
  default:
    external: true
    name: local
