version: "3"

services:
  rancher:
    image: rancher/rancher
    container_name: rancher
    hostname: rancher
    privileged: true
    ports:
      - 8443:443
    volumes:
      - /d/share/:/d/share/

networks:
  default:
    external: true
    name: local
