services:
  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: redis
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/bitnami/redis

networks:
  default:
    external: true
    name: compose

volumes:
  redis:
