version: '3'

services:
  neo4j:
    image: neo4j:4.3
    container_name: neo4j
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data/:/data/
      - neo4j_logs:/logs/

networks:
  default:
    external: true
    name: local_net

volumes:
  neo4j_logs:
    name: neo4j_logs