ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    nodePort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 80
    nodePort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    nodePort: 80
    protocol: TCP

service:
  type: NodePort
