version: '3'

services:
  postgresql:
    image: postgres:13
    container_name: postgresql
    hostname: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

networks:
  default:
    external: true
    name: local_net

volumes:
  postgresql_data:
    external: true
    name: postgresql_data