services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 2181:2181
    volumes:
      - zookeeper:/bitnami/zookeeper

networks:
  default:
    external: true
    name: compose

volumes:
  zookeeper:
