version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 9200:9200
    volumes:
      - ../../data/elasticsearch/usr/share/elasticsearch/data/:/usr/share/elasticsearch/data/
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    hostname: kibana
    environment:
      - 'I18N_LOCALE=zh-CN'
      - 'ELASTICSEARCH-HOSTS=http://elasticsearch:9200'
    ports:
      - 5601:5601

networks:
  default:
    external: true
    name: local