databaseName: readwrite_splitting_db

dataSources:
  primary_ds:
    url: jdbc:mysql://192.192.192.101:3306/demo
    username: root
    password: root
  replica_ds_0:
    url: jdbc:mysql://192.192.192.101:3307/demo
    username: root
    password: root
  replica_ds_1:
    url: jdbc:mysql://192.192.192.101:3308/demo
    username: root
    password: root

rules:
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_ds:
        staticStrategy:
          writeDataSourceName: primary_ds
          readDataSourceNames:
            - replica_ds_0
            - replica_ds_1
        loadBalancerName: random
    loadBalancers:
      random:
        type: RANDOM
