version: "3.8"
services:
  es0:
    image: elasticsearch:7.8.0
    # restart: always
    ports:
      - 9200:9200
    volumes:
      # - ./es0/data/:/usr/share/elasticsearch/data/
      - ./es0/plugins/:/usr/share/elasticsearch/plugins/
    environment:
      - node.name=es0
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  default:
    external:
      name: local-net
