version: '3'
services:
  nacos:
    image: nacos/nacos-server
    # restart: always
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
    ports:
      - 8848:8848
    volumes:
      - ./nacos/logs/:/home/nacos/logs/
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties

networks:
  default:
    external:
      name: local-net
