services:
  influxdb:
    image: bitnami/influxdb:2
    container_name: influxdb
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_USER_PASSWORD: admin123
      INFLUXDB_ADMIN_USER_TOKEN: admin
      INFLUXDB_USER_BUCKET: demo
    ports:
      - 8086:8086
    volumes:
      - influxdb:/bitnami/influxdb

networks:
  default:
    name: compose
    external: true

volumes:
  influxdb:
