version: '3'

services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    environments:
      - JVMFLAGS=-Dzookeeper.DigestAuthenticationProvider.superDigest=super:xQJmxLMiHGwaqBvst5y6rkB6HQs=
    ports:
      - 2181:2181
    volumes:
      - /d/share/:/d/share/
      - ../../data/zookeeper/data/:/data/
      - ../../data/zookeeper/datalog/:/datalog/

networks:
  default:
    external: true
    name: local
