version: "3"

services:
  postgresql:
    image: postgres:14
    container_name: postgresql
    hostname: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /d/share/:/d/share/
      - postgresql-data:/var/lib/postgresql/data/

networks:
  default:
    external: true
    name: local
volumes:
  postgresql-data:
    external: true
