version: '3'

services:
  clickhouse-server:
    image: yandex/clickhouse-server:21.7
    container_name: clickhouse-server
    hostname: clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./clickhouse-server/var/lib/clickhouse/:/var/lib/clickhouse/
  
networks:
  default:
    external: true
    name: local