fullnameOverride: coredns
serviceType: NodePort
prometheus:
  service:
    enabled: true
service:
  name: coredns
  clusterIP: 10.16.0.10
servers:
  - zones:
      - zone: .
    port: 53
    nodePort: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      - name: etcd
        configBlock: |-
          path /skydns
          endpoint http://192.168.31.101:2379
          fallthrough
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
