services:
  mysql-ds0:
    image: mysql:8.0
    container_name: mysql-ds0
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=1
      - --lower-case-table-names=1
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+8:00
    ports:
      - 3306:3306
    volumes:
      - mysql-ds0-data:/var/lib/mysql
  mysql-ds1:
    image: mysql:8.0
    container_name: mysql-ds1
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=2
      - --lower-case-table-names=1
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+8:00
    ports:
      - 3307:3306
    volumes:
      - mysql-ds1-data:/var/lib/mysql

networks:
  default:
    external: true
    name: compose

volumes:
  mysql-ds0-data:
  mysql-ds1-data:
