services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.19.4
    container_name: portainer
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

networks:
  default:
    name: compose
    external: true

volumes:
  portainer-data:
