security:
  oauth2:
    client:
      client-id: client2
      client-secret: client2
      user-authorization-uri: http://localhost:1000/sso-auth/oauth/authorize
      access-token-uri: http://localhost:1000/sso-auth/oauth/token
    resource:
      token-info-uri: http://localhost:1000/sso-auth/oauth/check_token

server:
  port: 1200

