/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.codegen.maven.example.tables.Author;
import org.jooq.codegen.maven.example.tables.Book;
import org.jooq.codegen.maven.example.tables.BookStore;
import org.jooq.codegen.maven.example.tables.BookToBookStore;
import org.jooq.codegen.maven.example.tables.Language;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.author</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>test.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>test.book_store</code>.
     */
    public final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>test.book_to_book_store</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>test.language</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Language.LANGUAGE
        );
    }
}
