version: '3'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/

networks:
  default:
    external: true
    name: local

volumes:
  mongodb_data:
    external: true
    name: mongodb_data