version: '3'

services:
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    # restart: always
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper/conf/zoo.cfg:/conf/zoo.cfg
      - ./zookeeper/data/:/data/
      - ./zookeeper/datalog/:/datalog/

networks:
  default:
    external:
      name: local-net
