version: '3'

services: 
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    # restart: always
    ports: 
      - 2181:2181
    volumes: 
      - ./zookeeper/conf/zoo.cfg:/conf/zoo.cfg

networks:
  default:
    external:
      name: local-net