version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.9.0
    container_name: portainer
    hostname: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data/:/data/

networks:
  default:
    external: true
    name: local