server:
  port: 8081
spring:
  application:
    name: business-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.192.192.101:8848
        namespace: public
        username: nacos
        password: nacos

seata:
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 192.192.192.101:8091
