spring:
  application:
    name: ZUUL
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  routes:
    microservice-ware:
      path: /ware/**
      serviceId: MICROSERVICE-WARE
    microservice-payment:
      path: /payment/**
      serviceId: MICROSERVICE-PAYMENT
    microservie-order:
      path: /order/**
      serviceId: MICROSERVICE-ORDER

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
