version: '3'

services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    # restart: always
    ports:
      - 9000:9000
    volumes:
      - ./portainer/data/:/data/

networks:
  default:
    external:
      name: standalone-net
