version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data/:/usr/share/nginx/html/

networks:
  default:
    external:
      name: local-net
