version: "3"

services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos
    hostname: nacos
    environment:
      - MODE=standalone
    ports:
      - 8848:8848
    volumes:
      - ../../data/nacos/home/nacos/logs/:/home/nacos/logs/

networks:
  default:
    external: true
    name: local
