version: '3'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - /d/share/:/d/share/
      - ../../data/mongodb/data/:/data/
  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    hostname: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=mongo-express
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo-express
    ports:
      - 27081:8081

networks:
  default:
    external: true
    name: local
