services:
  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=mongo-express
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo-express
    ports:
      - 27081:8081
    volumes:
      - /d/share/:/d/share/

networks:
  default:
    external: true
    name: local
