version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/http/:/etc/nginx/http/
      - ../../data/nginx/data/:/data/

networks:
  default:
    external: true
    name: local