services:
  hive-metastore:
    image: docker.io/apache/hive:4.0.0-beta-1
    container_name: hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgresql:5432/hive
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
    ports:
      - 9083:9083
    volumes:
      - ./postgresql-42.7.2.jar:/opt/hive/lib/postgresql-42.7.2.jar

  hive-hiveserver2:
    image: docker.io/apache/hive:4.0.0-beta-1
    container_name: hive-hiveserver2
    environment:
      SERVICE_NAME: hiveserver2
      IS_RESUME: true
      SERVICE_OPTS: >-
        -Dhive.metastore.uris=thrift://metastore:9083
    ports:
      - 10000:10000
      - 10002:10002
    volumes:
      - hive-data:/opt/hive/data/warehouse

networks:
  default:
    name: compose
    external: true

volumes:
  hive-data:
