services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=1
      - --lower-case-table-names=1
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+8:00
    ports:
      - 3306:3306
    volumes:
      - mysql-master-data:/var/lib/mysql
  mysql-slave1:
    image: mysql:8.0
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=2
      - --lower-case-table-names=1
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+8:00
    ports:
      - 3307:3306
    volumes:
      - mysql-slave1-data:/var/lib/mysql
  mysql-slave2:
    image: mysql:8.0
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=3
      - --lower-case-table-names=1
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+8:00
    ports:
      - 3308:3306
    volumes:
      - mysql-salve2-data:/var/lib/mysql

networks:
  default:
    external: true
    name: compose

volumes:
  mysql-master-data:
  mysql-slave1-data:
  mysql-salve2-data:
