version: '3'

services:
  rocketmq-namesrv:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-namesrv
    # restart: always
    ports:
      - 9876:9876
    environment:
      - 'JAVA_OPT_EXT=-Xms512m -Xmx512m'
    command: ['sh', 'mqnamesrv']

  rocketmq-broker-a:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-broker-a
    # restart: always
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./rocketmq-broker-a/home/rocketmq/broker.conf:/home/rocketmq/broker.conf
      - ./rocketmq-broker-a/home/rocketmq/store/:/home/rocketmq/store/
    environment:
      - 'JAVA_OPT_EXT=-Xms512m -Xmx512m'
    command: ['sh', 'mqbroker', '-c', '/home/rocketmq/broker.conf']

networks:
  default:
    external:
      name: local-net
