adminPassword: admin

externalURL: http://core.harbor.dev.icefery.xyz

exposureType: ingress

ingress:
  core:
    hostname: core.harbor.dev.icefery.xyz
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  notary:
    hostname: notary.harbor.tc.icefery.xyz
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"