expose:
  tls:
    enabled: true
  ingress:
    hosts:
      core: core.harbor.dev.icefery.xyz
      notary: notary.harbor.dev.icefery.xyz

externalURL: https://core.harbor.dev.icefery.xyz

harborAdminPassword: 'admin'
