version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    ports:
      - 9000:9000
    volumes:
      - ../../data/portainer/data/:/data/

networks:
  default:
    external: true
    name: local
