### create
POST http://localhost:8080/user/create
Content-Type: application/json

{
  "username": "icefery",
  "email": "icefery@163.com"
}


### findList
GET http://127.0.0.1:8080/user/find-list?email=u1@gmail.com


### find
GET http://127.0.0.1:8080/user/find?id=1


### find
GET http://127.0.0.1:8080/user/find?username=u0000


### update
PUT http://127.0.0.1:8080/user/update
Content-Type: application/json

{
  "id": 1,
  "username": "u1",
  "email": "u1@163.com"
}


### delete
DELETE http://127.0.0.1:8080/user/delete?id=1
