services:
  kafka:
    image: bitnami/kafka:3
    container_name: kafka
    hostname: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092
    volumes:
      - /d/share/:/d/share/
      - /d/mount/kafka/bitnami/kafka/:/bitnami/kafka/

networks:
  default:
    external: true
    name: local
