version: '3'

services: 
  zookeeper: 
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    ports: 
      - 2181:2181
    volumes: 
      - zookeeper_data:/data/
      - zookeeper_datalog:/datalog/
      - zookeeper_logs:/logs/
    
networks: 
  default:
    external: true
    name: local

volumes: 
  zookeeper_data:
  zookeeper_datalog:
  zookeeper_logs: