version: '3.8'

services:
  mysql0:
    image: mysql
    restart: always
    privileged: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql0/conf/conf.d/:/etc/mysql/conf.d/
      - ./mysql0/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  default:
    external:
      name: local-net
