---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
spec:
  selector:
    app: seaweedfs
  type: LoadBalancer
  ports:
    - { name: master-http, port: 9333, targetPort: 9333 }
    - { name: filer-http, port: 8888, targetPort: 8888 }
    - { name: s3-http, port: 8333, targetPort: 8333 }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
  labels:
    app: seaweedfs
spec:
  selector:
    matchLabels:
      app: seaweedfs
  template:
    metadata:
      labels:
        app: seaweedfs
    spec:
      containers:
        - name: seaweedfs
          image: docker.io/bitnami/seaweedfs:3.69.0
          args: ["server", "-dir=/data", "-s3"]
          ports:
            - { name: master-http, containerPort: 9333 }
            - { name: filer-http, containerPort: 8888 }
            - { name: s3-http, containerPort: 8333 }
          volumeMounts:
            - { name: seaweedfs-data, mountPath: /data }
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
      volumes:
        - name: seaweedfs-data
          emptyDir:
