spring:
  shardingsphere:
    # 模式配置
    mode:
      type: Standalone
    # 数据源配置
    datasource:
      names: master,slave1,slave2
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.192.192.101:3306/demo
        username: root
        password: root
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.192.192.101:3307/demo
        username: root
        password: root
      slave2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.192.192.101:3308/demo
        username: root
        password: root
    # 规则配置
    rules:
      # 读写分离
      readwrite-splitting:
        data-sources:
          my_ds:
            load-balancer-name: my_lb
            # 静态读写分离
            static-strategy:
              write-data-source-name: master
              read-data-source-names: slave1,slave2
        # 负责均衡算法配置
        load-balancers:
          my_lb:
            type: ROUND_ROBIN
    props:
      sql-show: true
