services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /d/share/:/d/share/
      - /d/mount/rabbitmq/var/lib/rabbitmq/:/var/lib/rabbitmq/

networks:
  default:
    external: true
    name: local
