services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /d/share/:/d/share/
      - /var/run/docker.sock:/var/run/docker.sock
      - /d/mount/portainer/data/:/data/

networks:
  default:
    external: true
    name: local
