SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for questionnaire
-- ----------------------------
DROP TABLE IF EXISTS `questionnaire`;
CREATE TABLE `questionnaire`  (
  `id` bigint NOT NULL COMMENT '问卷ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '问卷标题',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '问卷描述',
  `questions` json NOT NULL COMMENT '问卷项默认内容',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '问卷' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of questionnaire
-- ----------------------------
INSERT INTO `questionnaire` VALUES (1349622206322548737, 1349363369443135490, '测试问卷', '测试问卷描述', '[{\"type\": \"qa\", \"title\": \"姓名\", \"value\": \"\", \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"radio\", \"title\": \"性别\", \"value\": {\"checked\": \"男\", \"options\": [\"男\", \"女\"]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 2}, \"required\": true}, {\"type\": \"checkbox\", \"title\": \"英雄\", \"value\": [{\"name\": \"花木兰\", \"checked\": false}, {\"name\": \"百里玄策\", \"checked\": false}, {\"name\": \"关羽\", \"checke\": false, \"checked\": false}], \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 3}, \"required\": true}, {\"type\": \"location\", \"title\": \"位置\", \"value\": {\"area\": \"新都区\", \"city\": \"成都市\", \"province\": \"四川省\"}, \"config\": {\"locationParams\": [{\"name\": \"省\", \"value\": \"province\", \"checked\": true}, {\"name\": \"市\", \"value\": \"city\", \"checked\": true}, {\"name\": \"区\", \"value\": \"area\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"datetime\", \"title\": \"生日\", \"value\": {\"day\": 14, \"hour\": 15, \"year\": 2021, \"month\": 1, \"minute\": 39, \"second\": 23}, \"config\": {\"datetimeParams\": [{\"name\": \"年\", \"value\": \"year\", \"checked\": true}, {\"name\": \"月\", \"value\": \"month\", \"checked\": true}, {\"name\": \"日\", \"value\": \"day\", \"checked\": true}, {\"name\": \"时\", \"value\": \"hour\", \"checked\": true}, {\"name\": \"分\", \"value\": \"minute\", \"checked\": true}, {\"name\": \"秒\", \"value\": \"second\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}]');
INSERT INTO `questionnaire` VALUES (1349650903930830850, 1349363369443135490, '测试问卷标题', '测试问卷描述', '[{\"type\": \"qa\", \"title\": \"姓名\", \"value\": \"\", \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"radio\", \"title\": \"性别\", \"value\": {\"checked\": \"男\", \"options\": [\"男\", \"女\"]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 2}, \"required\": true}, {\"type\": \"checkbox\", \"title\": \"常用英雄\", \"value\": [{\"name\": \"花木兰\", \"checked\": false}, {\"name\": \"百里玄策\", \"checked\": false}, {\"name\": \"关羽\", \"checke\": false, \"checked\": false}, {\"name\": \"东方耀\", \"checke\": false, \"checked\": true}], \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 4}, \"required\": true}, {\"type\": \"location\", \"title\": \"当前位置\", \"value\": {\"area\": \"新都区\", \"city\": \"成都市\", \"province\": \"四川省\"}, \"config\": {\"locationParams\": [{\"name\": \"省\", \"value\": \"province\", \"checked\": true}, {\"name\": \"市\", \"value\": \"city\", \"checked\": true}, {\"name\": \"区\", \"value\": \"area\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"datetime\", \"title\": \"哪一刻她变成了光\", \"value\": {\"day\": 14, \"hour\": 17, \"year\": 2021, \"month\": 1, \"minute\": 32, \"second\": 17}, \"config\": {\"datetimeParams\": [{\"name\": \"年\", \"value\": \"year\", \"checked\": true}, {\"name\": \"月\", \"value\": \"month\", \"checked\": true}, {\"name\": \"日\", \"value\": \"day\", \"checked\": true}, {\"name\": \"时\", \"value\": \"hour\", \"checked\": true}, {\"name\": \"分\", \"value\": \"minute\", \"checked\": true}, {\"name\": \"秒\", \"value\": \"second\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}]');
INSERT INTO `questionnaire` VALUES (1349905107603263489, 1349363369443135490, '测试1', '0000', '[{\"type\": \"qa\", \"title\": \"a\", \"value\": \"\", \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"radio\", \"title\": \"\", \"value\": {\"checked\": \"选项 1\", \"options\": [\"选项 1\", \"选项 2\"]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 2}, \"required\": true}, {\"type\": \"checkbox\", \"title\": \"\", \"value\": [{\"name\": \"选项 1\", \"checked\": true}, {\"name\": \"选项 2\", \"checked\": true}], \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 2}, \"required\": true}]');
INSERT INTO `questionnaire` VALUES (1349905386704834562, 1349363369443135490, '测试1', '0000', '[{\"type\": \"qa\", \"title\": \"a\", \"value\": \"\", \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"datetime\", \"title\": \"\", \"value\": {\"day\": 15, \"hour\": 10, \"year\": 2021, \"month\": 1, \"minute\": 24, \"second\": 38}, \"config\": {\"datetimeParams\": [{\"name\": \"年\", \"value\": \"year\", \"checked\": true}, {\"name\": \"月\", \"value\": \"month\", \"checked\": true}, {\"name\": \"日\", \"value\": \"day\", \"checked\": true}, {\"name\": \"时\", \"value\": \"hour\", \"checked\": true}, {\"name\": \"分\", \"value\": \"minute\", \"checked\": true}, {\"name\": \"秒\", \"value\": \"second\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"checkbox\", \"title\": \"\", \"value\": [{\"name\": \"选项 1\", \"checked\": true}, {\"name\": \"选项 2\", \"checked\": true}], \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 2}, \"required\": true}]');

-- ----------------------------
-- Table structure for questionnaire_item
-- ----------------------------
DROP TABLE IF EXISTS `questionnaire_item`;
CREATE TABLE `questionnaire_item`  (
  `id` bigint NOT NULL COMMENT '问卷项ID',
  `questionnaire_id` bigint NOT NULL COMMENT '问卷ID',
  `tenant_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '租户ID',
  `questions` json NOT NULL COMMENT '问题',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '问卷项表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of questionnaire_item
-- ----------------------------
INSERT INTO `questionnaire_item` VALUES (1349685921243742209, 1349650903930830850, '1349363369443135490', '[{\"type\": \"qa\", \"title\": \"姓名\", \"value\": \"教主\", \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"radio\", \"title\": \"性别\", \"value\": {\"checked\": \"男\", \"options\": [\"男\", \"女\"]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 2}, \"required\": true}, {\"type\": \"checkbox\", \"title\": \"常用英雄\", \"value\": [{\"name\": \"花木兰\", \"checked\": true}, {\"name\": \"百里玄策\", \"checked\": true}, {\"name\": \"关羽\", \"checke\": false, \"checked\": true}, {\"name\": \"东方耀\", \"checke\": false, \"checked\": true}], \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 4}, \"required\": true}, {\"type\": \"location\", \"title\": \"当前位置\", \"value\": {\"area\": \"新都区\", \"city\": \"成都市\", \"province\": \"四川省\"}, \"config\": {\"locationParams\": [{\"name\": \"省\", \"value\": \"province\", \"checked\": true}, {\"name\": \"市\", \"value\": \"city\", \"checked\": true}, {\"name\": \"区\", \"value\": \"area\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"datetime\", \"title\": \"哪一刻她变成了光\", \"value\": {\"day\": 14, \"hour\": 17, \"year\": 2021, \"month\": 1, \"minute\": 32, \"second\": 17}, \"config\": {\"datetimeParams\": [{\"name\": \"年\", \"value\": \"year\", \"checked\": true}, {\"name\": \"月\", \"value\": \"month\", \"checked\": true}, {\"name\": \"日\", \"value\": \"day\", \"checked\": true}, {\"name\": \"时\", \"value\": \"hour\", \"checked\": true}, {\"name\": \"分\", \"value\": \"minute\", \"checked\": true}, {\"name\": \"秒\", \"value\": \"second\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}]');
INSERT INTO `questionnaire_item` VALUES (1349904953592614913, 1349650903930830850, '1349363369443135490', '[{\"type\": \"qa\", \"title\": \"姓名\", \"value\": \"\", \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"radio\", \"title\": \"性别\", \"value\": {\"checked\": \"男\", \"options\": [\"男\", \"女\"]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 2}, \"required\": true}, {\"type\": \"checkbox\", \"title\": \"常用英雄\", \"value\": [{\"name\": \"花木兰\", \"checked\": false}, {\"name\": \"百里玄策\", \"checked\": false}, {\"name\": \"关羽\", \"checke\": false, \"checked\": false}, {\"name\": \"东方耀\", \"checke\": false, \"checked\": true}], \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false, \"cachedOptionNo\": 4}, \"required\": true}, {\"type\": \"location\", \"title\": \"当前位置\", \"value\": {\"area\": \"波密县\", \"city\": \"林芝市\", \"province\": \"西藏自治区\"}, \"config\": {\"locationParams\": [{\"name\": \"省\", \"value\": \"province\", \"checked\": true}, {\"name\": \"市\", \"value\": \"city\", \"checked\": true}, {\"name\": \"区\", \"value\": \"area\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}, {\"type\": \"datetime\", \"title\": \"哪一刻她变成了光\", \"value\": {\"day\": \"14\", \"hour\": \"21\", \"year\": \"2023\", \"month\": \"01\", \"minute\": \"35\", \"second\": \"21\"}, \"config\": {\"datetimeParams\": [{\"name\": \"年\", \"value\": \"year\", \"checked\": true}, {\"name\": \"月\", \"value\": \"month\", \"checked\": true}, {\"name\": \"日\", \"value\": \"day\", \"checked\": true}, {\"name\": \"时\", \"value\": \"hour\", \"checked\": true}, {\"name\": \"分\", \"value\": \"minute\", \"checked\": true}, {\"name\": \"秒\", \"value\": \"second\", \"checked\": true}]}, \"control\": {\"swipeShow\": false, \"uploadRef\": null, \"pickerShow\": false}, \"required\": true}]');

-- ----------------------------
-- Table structure for tenant
-- ----------------------------
DROP TABLE IF EXISTS `tenant`;
CREATE TABLE `tenant`  (
  `id` bigint NOT NULL COMMENT '租户ID',
  `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '租户账号',
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '租户密码',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '租户表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant
-- ----------------------------
INSERT INTO `tenant` VALUES (1349363369443135490, 'icefery', '$2a$10$Shl8ciHJrSKZ04Zj7.hOKOZVzHUXoS3KbrZwIMlfPJ8TnvUiLv5fy');

SET FOREIGN_KEY_CHECKS = 1;
