spring:
  application:
    name: elasticsearch-demo
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      username: elastic
      password: 123456
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: test
      replica-set-name: replica-set
  thymeleaf:
    cache: false
