services:
  mongo-express:
    image: docker.io/library/mongo-express:1.0.2-20
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: mongo-express
      ME_CONFIG_BASICAUTH_PASSWORD: mongo-express
    ports:
      - 27081:8081

networks:
  default:
    name: compose
    external: true
