version: '3'

services:
  nginx:
    image: nginx:1.19
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/usr/share/nginx/html/:/usr/share/nginx/html/

networks:
  default:
    external:
      name: local-net
