deployment:
  kind: Deployment

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowEmptyServices: true
    publishedService:
      enabled: true

ports:
  traefik:
    port: 9000
    protocol: TCP
    expose: true
    exposedPort: 9000
  metrics:
    port: 9100
    protocol: TCP
    expose: true
    exposedPort: 9100
  web:
    port: 80
    protocol: TCP
    expose: true
    exposedPort: 80
  websecure:
    port: 443
    protocol: TCP
    expose: true
    exposedPort: 443
    tls:
      enabled: true

service:
  type: LoadBalancer

securityContext:
  capabilities:
    drop: []
    add:
      - ALL
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

podSecurityContext:
  fsGroup: 0
