services:
  opengauss:
    image: docker.io/opengauss/opengauss:5.0.0
    container_name: opengauss
    environment:
      GS_PASSWORD: opengauss
    ports:
      - 5432:5432
    volumes:
      - opengauss-data:/var/lib/opengauss/data

networks:
  default:
    name: compose
    external: true

volumes:
  opengauss-data:
