services:
  nexus:
    image: sonatype/nexus3:3.41.0
    container_name: nexus
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data

networks:
  default:
    external: true
    name: compose

volumes:
  nexus-data:
