version: '3'
services:
  mongo_27017:
    image: mongo
    restart: always
    privileged: true
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
