services:
  nacos:
    image: nacos/nacos-server:2.1.0
    container_name: nacos
    environment:
      MODE: standalone
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849

networks:
  default:
    external: true
    name: compose
