version: '3'

services: 
  redisinsight: 
    image: redislabs/redisinsight
    # restart: always
    ports: 
      - 8001:8001
    volumes: 
      - ./redisinsight/data/:/db

networks: 
  default: 
    external: 
      name: local-net