services:
  kafka:
    image: docker.io/bitnami/kafka:3.2
    container_name: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - 9092:9092
    volumes:
      - kafka:/bitnami/kafka

networks:
  default:
    external: true
    name: compose

volumes:
  kafka:
