services:
  postgresql:
    image: bitnami/postgresql:14.5.0
    container_name: postgresql
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: postgres
      POSTGRESQL_DATABASE: demo
      POSTGRESQL_USERNAME: demo
      POSTGRESQL_PASSWORD: demo
    ports:
      - 5432:5432
    volumes:
      - postgresql:/bitnami/postgresql

networks:
  default:
    external: true
    name: compose

volumes:
  postgresql:
