services:
  postgresql:
    image: postgres:14.4
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /d/mount/postgresql/var/lib/postgresql/data/:/var/lib/postgresql/data/

networks:
  default:
    external: true
    name: dev
