global:
  postgresql:
    auth:
      postgresPassword: postgres
      username: demo
      password: demo
      database: demo

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 5432