services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /d/share/:/d/share/
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/http/:/etc/nginx/http/
      - /d/mount/nginx/data/:/data/

networks:
  default:
    external: true
    name: local
